name: Deploy frontend to Azure Storage Static Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload to Azure Blob Static Website
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --source frontend \
              --destination '$web' \
              --sas-token "${{ secrets.AZURE_STORAGE_SAS_URL }}"
